refactor: fix semantic linebreaks (#46)
Enforce semantic linebreaks and fix all occurrences.

Add SARIF formatter and use sarif-upload action to show them in the PR.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,5 +29,25 @@ jobs:
         run: uv lock --locked
       - name: Run pre-commit
         uses: pre-commit/action@v3.0.1
+      - name: Run markdownlint
+        uses: YannickTeKulve/docker-run-action@0.0.6
+        with:
+          image: davidanson/markdownlint-cli2-rules:v0.14.0
+          # node user does not have permissions to workspace due to user id mismatch
+          options: -v ${{ github.workspace }}:/workdir --user root
+          # don't fail step if there are violations
+          run: markdownlint-cli2 --config .github/markdownlint/.markdownlint-cli2.yaml "**/*.md" || true
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          # Path to SARIF file relative to the root of the repository
+          sarif_file: markdownlint-cli2-sarif.sarif
+          # Optional category for the results
+          # Used to differentiate multiple results for one commit
+          category: markdownlint
+      # fail if there are markdownlint violations
+      - name: Check markdownlint results
+        run: |
+          cat markdownlint-cli2-sarif.sarif | grep -q '"results": \[\]'
       - name: Build mkdocs site
         run: uv run mkdocs build --strict
